### ISSUE TITLE
uniq_ML field unset in Python API

### ISSUE THREAD

**Issue by HWaymentSteele** [ViennaRNA/ViennaRNA#35] opened 2018-07-06 19:45 UTC
Hello!  I'm using the Python wrapper and am trying to sample structures using pbacktrack.  I know md.uniq_ML must be set to > 0 to use pbacktrack, but when I run the code below, I get the warning "Unique multiloop decomposition is unset!" and no output.  Am I doing something wrong?  Many thanks for your help!

```seq="GAAAAACCCCCCCCC"
mdl = RNA.md()
mdl.uniq_ML=1
fc = RNA.fold_compound(seq, mdl)
fc.pf()
fc.pbacktrack()

**Comment by RaumZeit** [comment] 2018-07-10 09:48
Hi. Does this issue appear with the latest release of the ViennaRNA Package?
I can't reproduce this behavior, but it might be that you are using an older version, where the `RNA.md()` constructor didn't yield a fully-accessible model object. Hence, setting `md1.uniq_ML=1` would only extend the model on the Python side, without passing the changes through to the C library.
Could you please check, what your `RNA.__version__` is, and whether `RNA.md().uniq_ML` is an integer attribute?

**Comment by RaumZeit** [comment] 2018-08-06 09:14
I'm closing this issue for now, since I was unable to reproduce the problem and there has been no update within the last month. Feel free to re-open it with a detailed description including the version number, if the problem persists.

**Closed by RaumZeit** 2018-08-06 09:14 UTC
