### ISSUE TITLE
Error "'av_top_index' was not declared in this scope" occurs 'make' of ViennaRNA-2.6.4 in CentOS

### ISSUE THREAD

**Issue by hawkchow2016** [ViennaRNA/ViennaRNA#228] opened 2024-04-27 03:12 UTC
After './configure'， Error "'av_top_index' was not declared in this scope" occurs 'make' of ViennaRNA-2.6.4 in CentOS
![微信图片_20240427111148](https://github.com/ViennaRNA/ViennaRNA/assets/168252294/14e1c8ca-1e7f-4311-8bab-21f4884034b0)
what should I do to fix this?

**Comment by RaumZeit** [comment] 2024-04-29 06:55
Seems like the Perl 5 headers are unavailable!
Please try installing `perl-devel` or something similar first and re-run the `./configure` tool-chain. Alternatively, deactivate the Perl 5  interface if you don't need it, using the `--without-perl` `./configure` switch.

**Comment by RaumZeit** [comment] 2024-05-06 11:57
Hi, I just had a look at this again, and think the issue might also be due to an older Perl5 version. `av_top_index` was introduced with Perl 5.18.0. So, if you are running an older perl version, this might be the cause of the compilation error.
But I'm just guessing here, since I don't know any more of your `./configure` output and the pre-checks that have been made by our autoconf script.

I've adapted our code in the development branch to support older Perl5 versions again. With the next release this issue should be fixed. Until then, you may consider replacing all occurrences of `av_top_index` by `av_len` and re-compile. Both functions are virtually the same and the former has been introduced in v5.18.0 to avoid off-by-1 bugs in implementations that assume `av_len` would return the number of elements in an array...

**Closed** 2024-09-02 08:25 UTC
