### ISSUE TITLE
RNAfold --commands gives incorrect results

### ISSUE THREAD

**Issue by nirzi** [ViennaRNA/ViennaRNA#45] opened 2018-12-04 17:06 UTC
We are trying to use the `--commands` option in RNAfold in order to favor or disfavor specific pairs and we observed a strange behavior. In particular, we have a sequence that can form a duplex with different registers (`GGGGAAACCCC`) and try to favor a suboptimal one.

The command file contains only a term for pair 1-10:

````
> cat commands.dat
E 1 10 1 -3
````

We then run RNAfold -p to obtain the partition function and the pairing probabilities:
````
> echo GGGGAAACCCC | RNAfold -p --commands=commands.dat
GGGGAAACCCC
(((....))). ( -7.30)
(........). [ -7.31]
(........). {  0.20 d=0.18}
frequency of mfe structure in ensemble 0.986956; ensemble diversity 0.35 
> grep ubox dot.ps  | awk '{if($1+$2==11)print}'
1 10 0.994160021 ubox
2 9 0.087497215 ubox
3 8 0.087466674 ubox
`````

Surprisingly, as we enforce the formation of pair 1-10, the pairing probability of 2-9 and 3-8 remains very low. It is also very strange that the MFE structure appears correct, the total free energy of the ensemble (-7.31) is almost identical to the MFE (-7.30), but the ensemble is represented with only pair 1-10 formed.

We were wondering if this is a bug or if there is something that we do not understand in the way commands are specified to RNAfold.

Many thanks in advance!

**Comment by RaumZeit** [comment] 2018-12-13 15:18
Hi,
after some initial doubts that the results are wrong, **I indeed found a bug that causes this behavior**.
In fact, the problem is in the computation of the base pairing probabilities, where the underlying array for the soft constraints has been accessed in the wrong way.
I'm very sorry for the inconvenience, the bug will be fixed in the next version of the ViennaRNA Package which will be released within the next days!

Just for your information, I computed the base pair probabilities from an exhaustive enumeration of the ensemble to make sure that no other effects might _smear_ the probabilities. For that purpose, I used the following python code:
```
import RNA
import math


seq   = "GGGGAAACCCC"
kT    = 0.61632077549999997
pairs = [[ 0. for j in range(0, len(seq) + 1) ] for j in range(0, len(seq) + 1)]
pf    = 0.

fc = RNA.fold_compound(seq)
# add soft constraint for base pair (1,10)
fc.sc_add_bp(1,10,-3)

for s in fc.subopt(3000):
    # add contribution of structure to partition function
    pf = pf + math.exp(-s.energy / kT)
    # extract base pairs from structure
    pairtable = RNA.ptable(s.structure)
    for i in range(1, len(seq) + 1):
        if pairtable[i] > i:
            pairs[i][pairtable[i]] = pairs[i][pairtable[i]] + math.exp(-s.energy / kT)

print "Free energy of ensemble: %g\n" % ( -kT * math.log(pf))

for i in range(1, len(seq) + 1):
    for j in range(i + 1, len(seq) + 1):
        pairs[i][j] = pairs[i][j] / pf
        if pairs[i][j] > 0:
            print "pr(%d, %d) = %g" % (i, j, pairs[i][j])
```

In case you need a patch to fix this bug right-away, just drop another message.

Best,
Ronny

**Comment by RaumZeit** [comment] 2018-12-13 17:50
Here is the patch:
[https://www.tbi.univie.ac.at/~ronny/0001-Fix-wrong-access-to-base-pair-soft-constraints-in-eq.patch](https://www.tbi.univie.ac.at/~ronny/0001-Fix-wrong-access-to-base-pair-soft-constraints-in-eq.patch)

This should apply well to ViennaRNA Package 2.4.10 with:
```
cd ViennaRNA-2.4.10
patch -p1 <  0001-Fix-wrong-access-to-base-pair-soft-constraints-in-eq.patch
```

Thanks again for reporting the bug!

**Closed** 2018-12-18 19:38 UTC
