### ISSUE TITLE
Unable to replicate results of RNAcofold webserver using Python API

### ISSUE THREAD

**Issue by adam-dev-001** [ViennaRNA/ViennaRNA#238] opened 2024-06-26 17:26 UTC
Here is the run I am trying to replicate. Below, are the inputs: the two sample sequences, and using DNA parameters.

![image](https://github.com/ViennaRNA/ViennaRNA/assets/124276755/d49417a6-734c-4e49-9a66-89e4f50251c9)

Below are the results I am trying to replicate:
![image](https://github.com/ViennaRNA/ViennaRNA/assets/124276755/b39e1484-d698-44eb-bf38-2b59ebbd469d)

Specifically, I want to calculate the frequency of the MFE structure in the ensemble.

Here is the code I am using to try and replicate:
```
import RNA

seq1 = "ACGATCAGAGATCAGAGCATACGACAGCAG"
seq2 = "ACGAAAAAAAGAGCATACGACAGCAG"
RNA.params_load_DNA_Mathews2004()
md = RNA.md()

# change temperature and dangle model
md.temperature = 37.0 # 20 Deg Celcius

# create fold_compound data structure (required for all subsequently applied  algorithms)
fc = RNA.fold_compound(seq1 + "&" + seq2, md)


# compute MFE and MFE structure
(mfe_struct, mfe) = fc.mfe_dimer()

# rescale Boltzmann factors for partition function computation
fc.exp_params_rescale(mfe)

# compute partition function
pf_energy = fc.pf_dimer()


frequency = fc.pr_structure(mfe_struct)
```
I am getting the correct mfe_structure: ..((((...))))...((...((...((..............))...))...)).. 
And the correct minimum free energy: -4.699999809265137

However, my output for frequency is 0.0066 (instead of 11.21% as in the webserver) and for pf_energy is ['..((((...})))...,,...{,...,,..............,,...,,...}}..', -2.030135154724121, -0.8141905069351196, -6.7920403480529785, -6.793058395385742]

Am I missing something in my Python code or am I calculating the wrong thing?

Thank you very much!

**Comment by anthonyhtyao** [comment] 2024-06-27 14:14
The websever avoids lonely basepair by default while this is allowed in RNAlib by default, so we need to set the flag as
```py
md.noLP = 1
```
In addition, the frequency in webserver only considers AB dimer ensemble whose ensemble free energy is the second last value returned by pf_dimer(). We can also use pf() to get the same value. Therefore, one can reproduce the same result as below

```py
import RNA
from math import exp

seq1 = "ACGATCAGAGATCAGAGCATACGACAGCAG"
seq2 = "ACGAAAAAAAGAGCATACGACAGCAG"
RNA.params_load_DNA_Mathews2004()
md = RNA.md()
md.noLP = 1

def Boltzmann(e, temperature=37):
    kT = RNA.GASCONST * (temperature + RNA.K0) / 1000
    return exp(-e/kT)

fc = RNA.fold_compound(seq1 + "&" + seq2, md)
_, mfe = fc.mfe() # same as mfe_dimer
fc.exp_params_rescale(mfe)
# Get ensemble free energy of AB dimer
_, fee = fc.pf()

frequency = Boltzmann(mfe) / Boltzmann(fee)
# Get 0.1123
print(frequency)
```

**Comment by adam-dev-001** [comment] 2024-06-27 16:03
Thank you, that works! As a follow up, is there a python command/way to calculate it for interactions between more than two sequences as in RNAmultifold? Would we just concatenate and use RNA.fold_compound? Thank you.

**Comment by anthonyhtyao** [comment] 2024-06-27 18:27
yes, fold_compound takes multiple sequences with & as separator. The object will take care the rest backend

**Comment by adam-dev-001** [comment] 2024-06-28 14:20
Folding worked, however the partition function did not return all values and I am not sure what hetero/homo ensembles each value represents.
```
import RNA
from math import exp

seq1 = "ACGATCAGAGATCAGAGCATACGACAGCAG"
seq2 = "ACGAAAAAAAGAGCATACGACAGCAG"
seq3 = "AGGGGCCATGGCAGGCAGCGAGCGA"

RNA.params_load_DNA_Mathews2004()
md = RNA.md()
md.noLP = 1

def Boltzmann(e, temperature=37):
    kT = RNA.GASCONST * (temperature + RNA.K0) / 1000
    return exp(-e/kT)

fc = RNA.fold_compound(seq1 + "&" + seq2 + "&" + seq3, md)
_, mfe = fc.mfe() # same as mfe_dimer
fc.exp_params_rescale(mfe)
# Want to get ensemble free energy of ABC, ABB, AAB, AA, etc. as in the output of RNAmultifold -a
pf = fc.pf_dimer()
pf2 = fc.pf()
```
The output for **pf** is ['.,(,((...,,}}...,,...,,...,,..............||...,,...||......(({......}}).,},..),.', -1.5758601427078247, -7.612359523773193, -12.373858451843262, -12.37735652923584]
And the output for **pf2** is ['.,(,((...,,}}...,,...,,...,,..............||...,,...||......(({......}}).,},..),.', -12.373858451843262]
How do I make it so I get all possible ensemble free energies of the combinations of monomers from the partition function? I want to get ensemble free energy of ABC, ABB, AAB, AA, etc. as given in the output of **RNAmultifold -a**

Also, does the order we add the sequences matter? I.e. Will having potential a binding site on sequence 1 close to or far away from the point of concatenation (&) impact the binding of sequence 2 to that site? If it does, is there another function or workaround to address that variation?

Thank you very much

**Comment by anthonyhtyao** [comment] 2024-06-29 20:19
I'm not sure if multimer pf is wrapped in python side

**Comment by RaumZeit** [comment] 2024-09-02 07:40
2 months already passed, but I still want to comment on the multifold part of this question:
The `RNA.fold_compound().pf()` method does compute the partition function for a complex of the given input sequences. In particular, it computes the partition function for **one** specific arrangement, i.e. concatention, of the input sequences. In order to analyze the entire ensemble, one has to compute partition functions for each of the circular permutations of the input sequences. E.g. for 3 sequences A, B, and C, this is permutation ABC and ACB. In addition, if you want to compute ensemble energies for any other set of complexes, say AA, BB, etc., this needs to be done separately.

The `RNAmultifold` program does all that out of the box, but the python implementation (as well as `RNAlib`), so far, does not provide a one-does-all convenience function. Instead, it provides a set of helper functions that provide some necessary algorithms to efficiently enumerate the permutations.

For instance, assume, you have four distinct strands A, B, C, and D. Then you can use the `RNA.enumerate_necklaces()` function to generate all circular permuations for these sequences:
```.py
# sequence identifiers
seq_ids = ['A', 'B', 'C', 'D']
# number of occurences of the sequences
seq_num = [1, 1, 1 ,1]

# loop over all circular permutations of the four sequences
for p in RNA.enumerate_necklaces(seq_num):
    print([seq_ids[s] for s in p])
```

which yields:
```
['A', 'D', 'C', 'B']
['A', 'D', 'B', 'C']
['A', 'C', 'D', 'B']
['A', 'C', 'B', 'D']
['A', 'B', 'D', 'C']
['A', 'B', 'C', 'D']
```

This can then be used to concatenate the sequences in the corresponding order to subsequently create a fold_compound and compute ensemble energies. The total ensemble energy over all permutations can then be summed up via the `RNA.pf_add(dG1, dG2)` function, where `dG1` and `dG2` are two ensemble energies.

I hope this is already helpful for your project. Let me know if you require further assistance.
Cheers

**Comment by RaumZeit** [comment] 2024-09-02 08:15
Just a second thought about the things you want to compute: Since you are also interested in the homo-dimers and trimers, etc., there is another function in `RNAlib`, [`vrna_n_multichoose_k()`](https://viennarna.readthedocs.io/en/latest/utils/combinatorics.html#c.vrna_n_multichoose_k) that enumerates all possible combinations of the strands for complexes up of `k` interacting strands. However, this function has **not** been wrapped to Python before the upcoming version 2.7.0.

Starting with ViennaRNA 2.7.0 you can extend the above example like so:
```.py
for k in range(1, len(seq_ids) + 1):
    for s in RNA.n_multichoose_k(len(seq_ids), k):
        print([seq_ids[s] for s in s])
```
to retrieve all possible interactions that yield complexes up to `k` interacting strands:
```
['A']
['B']
['C']
['D']
['A', 'A']
['A', 'B']
['A', 'C']
['A', 'D']
['B', 'B']
['B', 'C']
['B', 'D']
['C', 'C']
['C', 'D']
['D', 'D']
['A', 'A', 'A']
['A', 'A', 'B']
['A', 'A', 'C']
['A', 'A', 'D']
['A', 'B', 'B']
['A', 'B', 'C']
['A', 'B', 'D']
['A', 'C', 'C']
['A', 'C', 'D']
['A', 'D', 'D']
['B', 'B', 'B']
['B', 'B', 'C']
['B', 'B', 'D']
['B', 'C', 'C']
['B', 'C', 'D']
['B', 'D', 'D']
['C', 'C', 'C']
['C', 'C', 'D']
['C', 'D', 'D']
['D', 'D', 'D']
['A', 'A', 'A', 'A']
['A', 'A', 'A', 'B']
['A', 'A', 'A', 'C']
['A', 'A', 'A', 'D']
['A', 'A', 'B', 'B']
['A', 'A', 'B', 'C']
['A', 'A', 'B', 'D']
['A', 'A', 'C', 'C']
['A', 'A', 'C', 'D']
['A', 'A', 'D', 'D']
['A', 'B', 'B', 'B']
['A', 'B', 'B', 'C']
['A', 'B', 'B', 'D']
['A', 'B', 'C', 'C']
['A', 'B', 'C', 'D']
['A', 'B', 'D', 'D']
['A', 'C', 'C', 'C']
['A', 'C', 'C', 'D']
['A', 'C', 'D', 'D']
['A', 'D', 'D', 'D']
['B', 'B', 'B', 'B']
['B', 'B', 'B', 'C']
['B', 'B', 'B', 'D']
['B', 'B', 'C', 'C']
['B', 'B', 'C', 'D']
['B', 'B', 'D', 'D']
['B', 'C', 'C', 'C']
['B', 'C', 'C', 'D']
['B', 'C', 'D', 'D']
['B', 'D', 'D', 'D']
['C', 'C', 'C', 'C']
['C', 'C', 'C', 'D']
['C', 'C', 'D', 'D']
['C', 'D', 'D', 'D']
['D', 'D', 'D', 'D']
```

For the time until the official release of ViennaRNA 2.7.0 you may use any other python implementation available elsewhere, e.g. [this one](https://github.com/ekg/multichoose/blob/master/multichoose.py)...

**Comment by RaumZeit** [comment] 2024-10-23 08:21
closing this issue for now, feel free to re-open if necessary!

**Closed by RaumZeit** 2024-10-23 08:21 UTC
