### ISSUE TITLE
Base pairing probability matrix per column/row sum exceeds 1

### ISSUE THREAD

**Issue by MikeACG** [ViennaRNA/ViennaRNA#213] opened 2023-10-25 21:03 UTC
Sometimes the sum of the columns/rows of the base pair probability matrices outputted by RNAfold or RNAplfold is greater than 1. Intuitively, I'd expect it to always be less than 1 with the sum of non-zero entries in the column/row representing the probability of the base pair to be paired with any other base pair and the complement of such probability to be the probability of being unpaired. I was wondering if this is actually a bug or if I'm just misunderstanding something. I have personally encountered the aforementioned case using the latest version of RNAplfold but also have found people [reporting this](https://www.biostars.org/p/314801/) for RNAfold (for an old version though). If this behavior is actually expected, could someone explain why and what the values of the matrix are actually representing in such case.

You can get a RNAplfold output matrix with columns summing more than 1 (e.g. The column for the 2nd base pair) with the following command:
`echo AGGAGCCGGAGGAGGAGCCGCCGCCGCCGTTGACCCGGCCGCCGGCCGGGAGCTGGGAGAGATGCGGAGCCCGGCCACCGGCGTCCCCCTCCCAACGCCGCCGCCGCCGCTGCTGCTGCTGTTGCTGCTGCTGCTGCCGCCGCCACTATTGGGAGACCAAGTGGGGCCCTGTCGTTCCTTGGGGTCCAGGGGACGAGGCTC | RNAplfold -W 200 -L 150 -c 0.01`

**Comment by MikeACG** [comment] 2023-10-25 21:24
Update: just found out through looking at closed issues (my bad, should have done this earlier) that what is reported in the matrices is the **square root of the probability**. Although this is explicitly stated in the .ps file I think it could also be useful to explicitly mention it in the documentation page for the programs. Feel free to close the issue if my interpretation of the probabilities is correct after taking the square of the base pair probabilities. Any special reason to report the square root instead of the raw probabilities? (I suspect its for plotting purposes but I'm curious)

**Comment by RaumZeit** [comment] 2023-10-26 08:17
Hi @MikeACG ,

there shouldn't be any probabilities larger than 1 in the output of `RNAfold`. If there are, then there is a bug in the computation of the probabilities. Please let us know which sequence produces the error such that we can try to reproduce the bug and eventually fix it.

On the other hand, for `RNAplfold`, the reported probabilities can easily exceed 1 since they represent expected values that are normalized over all windows the base pair can appear in, see also https://www.worldscientific.com/doi/10.1142/S0219720023500166 and https://academic.oup.com/bioinformatics/article/22/5/614/205542

Regarding the **square root** of the probability in the dot-plot output, I've to admit that this indeed is not stated in the `RNAplfold` manpage. This will be fixed in the next release. For `RNAfold`, however, this is mentioned in the [RNAfold manpage](https://viennarna.readthedocs.io/en/latest/man/RNAfold.html#description) as well as in our [Getting started tutorial](https://viennarna.readthedocs.io/en/latest/tutorial/RNAfold.html#the-base-pair-probability-dot-plot). I hope this is of any help for you and probably for others as well.

The actual reason for printing the square-root of the probabilities into the dot-plot is simply that probabilities are shown as squares with areas proportional to the probability, so the edge lengths of the squares are the square root of the respective probabilities...

Best,
Ronny

**Comment by MikeACG** [comment] 2023-10-26 08:49
Thank you so much for your answer!

**Closed** 2023-10-26 08:49 UTC
