### ISSUE TITLE
Losing base pairing probability for some bases when adding SHAPE

### ISSUE THREAD

**Issue by herber4** [ViennaRNA/ViennaRNA#231] opened 2024-05-11 13:01 UTC
Hello ViennaRNA, 

I am running RNAfold to calculate base pairing probabilities for some RNAs.

When I include normalized SHAPE data, produced from shapemapper2, I am losing base pairing probability information for some of the bases. : 
 
RNAfold -p --maxBPspan 200 --shape ATAD2B_shape.txt --noPS ATAD2B_sequence.txt > ATAD2B.out

However, when I don't include SHAPE data, I get a bpp for every base in column i. I need the base pairing probability at every base in column i as I am comparing splice sites at two different positions in this example.  

RNAfold -p --maxBPspan 200 --noPS ATAD2B_sequence.txt > ATAD2B.out

[ATAD2B_shape.txt](https://github.com/ViennaRNA/ViennaRNA/files/15282878/ATAD2B_shape.txt)

[ATAD2B_sequence.txt](https://github.com/ViennaRNA/ViennaRNA/files/15282880/ATAD2B_sequence.txt)

What should I adjust to still get bpp for every base I? I tried adjusting the --bppmThreshold to several different values or even 0 but it just produces NA for every base. 

Best, 

Austin

**Comment by RaumZeit** [comment] 2024-05-16 09:56
Hi, so basically this means that some nucleotides tend to do not pair under the guiding potential of the SHAPE data. However, using the `--bppmThreshold=0` parameter, I actually do get output for all nucleotides in the dot-plot EPS file using `RNAfold v2.6.4`:
```
RNAfold -p --maxBPspan 200 --bppmThreshold=0 --shape ATAD2B_shape.txt --noPS ATAD2B_sequence.txt > ATAD2B.out
cat ATAD2B_chr2_23754348_23755248_rc_dp.ps | perl -ne 'print $1,"\n" if /(\d+)\s+(\d+)\s+(\d\.\d+)\s+ubox/' | sort -k1,1n -u > a
for i in `seq 1 1 966`; do echo $i; done > b
diff a b
```
The diff is empty, so I can't reproduce this problem on my side... Where do you actually get the `NA` values from?

**Comment by herber4** [comment] 2024-05-16 13:48
Hi, it seems the SHAPE data for the rest of my samples was formatted incorrectly. Reformatting it corrected any issues. You can close this, sorry for the inconvenience!

Best, 

Austin

**Comment by herber4** [comment] 2024-05-16 14:06
side note, attached is a script I made to extract base pairing probabilities from the .ps files. you are welcome to distribute it as you see fits. 
[extract_bpp.txt](https://github.com/ViennaRNA/ViennaRNA/files/15336390/extract_bpp.txt)

**Comment by RaumZeit** [comment] 2024-06-18 08:51
thanks, I'll consider this and close the issue for now...

**Closed by RaumZeit** 2024-06-18 08:51 UTC
